# 数据库
mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: e_learn
  params: charset=utf8&parseTime=True&loc=Asia%2FShanghai

# 日志打印配置
logging:
  level: DEBUG
  short-file: true
  writer:
    - console
